### ISSUE TITLE
Integrate with the midburn DB

### ISSUE THREAD

**Issue by ripper234** [Midburn/playainfo#11]
@amotenko I assume the current setup is not connected to the Midburn production database.

We should do this, my preference is rather early than late, since integrations are always a risky part in a project.

What's the current database the system is using? Advantages of using the Midburn DB for everything is of course having it all in one place + backups etc (I assumed Midburn DB has backup :)).

@omerpines FYI, please give @amotenko the needed credentials. Note we need new tables there, and possibly read-only access to some tables - we do not need write access to any existing tables.

**Comment by omerpines** [comment]
It's a Stand alone system. Meaning not connected to any db, including Midburn's profiles. 
Why are we returning to this debate every time? 
All users are defined by relevant admin or content owner. No connection to db required at this point.

**Comment by ripper234** [comment]
@omerpines

For the current version of the system, no connection to any existing **tables** is required.
We do need, however, access to the database in order to store our own data. What we need is a few new tables that only we will use. We want to use the same database/server, because it doesn't make sense to open an entire new database for that.

In the future we might want READ access to some existing tables, but that's not for the current release anyway.

**Comment by omerpines** [comment]
You'll have to Open a new db. Drupal DB should not be touched. Ask Shay,  Dror or Oded for assistance in AWS.

**Comment by ripper234** [comment]
I only meant the same server, not the same physical database. A separate server for this will cost more.

Shay/Dror/Oded has AWS credentials to the DB?

**Comment by omerpines** [comment]
​I don't want anyone touching the Midburn DB. It is very delicate with
sensitive information. Please use a separate server for this.

You can ask any one of them for assistance in this. They all have
credentials to create a DB.

Omer
​

**Comment by ripper234** [comment]
From everything I know about servers (and I've done some serious work with
gbs of db tables), unless it's huge amounts of data, reusing servers does
not impact security, isolation or performance between different databases.
Also, it's way easier to maintain.

Would you like another opinion on this?

On Fri, Mar 4, 2016 at 3:05 AM, Omer Pines notifications@github.com wrote:

> ​I don't want anyone touching the Midburn DB. It is very delicate with
> sensitive information. Please use a separate server for this.
> 
> You can ask any one of them for assistance in this. They all have
> credentials to create a DB.
> 
> Omer
> ​
> 
> On Wed, Mar 2, 2016 at 12:54 PM, Ron Gross notifications@github.com
> wrote:
> 
> > I only meant the same server, not the same physical database. A separate
> > server for this will cost more.
> > 
> > Shay/Dror/Oded has AWS credentials to the DB?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Midburn/playainfo/issues/11#issuecomment-192044190.

## 

Ron Gross
Skype = ripper234, Schedule my time - meetme.so/RonGross
CNO http://www.chiefninjaofficer.com/

**Comment by amotenko** [comment]
Please let's not discuss this any longer. This is premature optimisation.
Let's focus on finding a UI designer.

**Comment by ripper234** [comment]
Yes

**Comment by ripper234** [comment]
Closing this for now, there is a separate ticket about deploying to a production DB.
We are not integrating with any existing databases for now.
