### ISSUE TITLE
Add Event

### ISSUE THREAD

**Issue by ripper234** [Midburn/playainfo#15]
When the "Create Event" button is pressed, a new expandable opens.

All the fields are mandatory
- English Event Name
- Hebrew Event Name
- Start Date & End Date (datepicker)
- Checkbox "Every Day" which when checked, hides & eliminates the date pickers (including in the data model)
- Start Time & End Time (timepicker)
- Checkbox "All the time" which when checked, hides & eliminates the time pickers.
- English Description
- Hebrew Description

Clicking the Submit button creates the event, clears all the fields, and collapses the expandable.

Clicking the Cancel button clears all the fields, collapses the expandable, **without** creating the event of course.

![image](https://cloud.githubusercontent.com/assets/172282/13602749/2ce5c95c-e541-11e5-84f5-32a4988ab82d.png)

**Comment by amotenko** [comment]
1. Some fields are missing.
2. If the event is created successfully (no errors), route the user back to the Events page (list all events).

**Comment by amotenko** [comment]
Need to add tags in the future
