### ISSUE TITLE
Delete Event

### ISSUE THREAD

**Issue by ripper234** [Midburn/playainfo#19]
In the  Content Provider Events page, there should be a Delete button next to each displayed event.
This event opens a confirm dialog box.

> Are you sure you want to delete this event?
> Really sure?

Two buttons, Cancel and Confirm (Confirm is not selected by default).

**Comment by amotenko** [comment]
Confirm is not yet implemented.
We should do either a confirm or an undo button.

**Comment by amotenko** [comment]
Implemented with confirmation dialogue
