### ISSUE TITLE
The location (if theme camp) should be a dropdown, not text name

### ISSUE THREAD

**Issue by ripper234** [Midburn/playainfo#2]
[The spec](https://github.com/Midburn/playainfo/pull/1/files), says (orgiinal text from Slack) that one of the fields we gather is location:

*מקום, אם זה מחנה נושא אז שם המחנה (עברית ואנגלית) 

Instead of gathering the name of the camp in text, we should use the same dropdown we do for the owner of the activity. If we do it via text entry this will just cause confusion because people will mispell their camp's name.

I propose we use the same "camp name" dropdown for this as well.

**Comment by omerpines** [comment]
You don't know where it will be (Example: a parade that starts somewhere in deap playa)
I've changed it to initially the camp name is provided but the user can change it.

**Comment by ripper234** [comment]
I think the ideal interface should be something like:

1st Dropdown where you can choose between (Salon, Camp, Other)
- If "Camp" is chosen, then you get a dropdown of camps.
- If Salon is chosen no further input is reuquired
- If Other is chosen, freetext.

I don't know how hard it is to implement within the system.

**Comment by omerpines** [comment]
I changed to group and subgroup since the same behavior happening in theme camp (many sub groups) occurs in production and art as well.

**Comment by ripper234** [comment]
> group and subgroup

What does this mean exactly?
Text based?

**Comment by omerpines** [comment]
Read the readme.
