### ISSUE TITLE
Export access links

### ISSUE THREAD

**Issue by amotenko** [Midburn/playainfo#26]
An admin needs a way to export a CSV.

Inpt: Content Group
Output: 

A CSV with the columns:
1. Content Provider Name (Hebrew)
2. Content Provider Name (English)
3. Access Link

**Comment by ripper234** [comment]
The exported CSV should contain a **link** to login, not just the uuid.

Example:

> http://playainfo.midburn.org/login/609ec08d-4a96-46d5-8b81-835af0dc641f

or 

> http://playainfo.midburn.org/login?token=17am1aK1l

What URL format are we using to login?
#16 is closed so I understand we have login functionality, but I don't know how to access it.
