### ISSUE TITLE
"Every Day" and "All Day" checkboxes should hide Date & Time pickers respectively

### ISSUE THREAD

**Issue by amotenko** [Midburn/playainfo#27]
The logic described at #15 about how All Day events + Recurring events is not yet implemented.

**Comment by ripper234** [comment]
As described in #15:

> Checkbox "Every Day" which when checked, hides & eliminates the date pickers (including in the data model)
> Start Time & End Time (timepicker)
> Checkbox "All the time" which when checked, hides & eliminates the time pickers.

Emphasis:
1. We talked about 'graying out' ... I prefer we actually hide the relevant picker, not just gray out.
2. Note - these work separately. The "Every Day" checkbox hides the _date picker_. **Separately**, the "All The Time" checkbox hides the **time picker**.

**Comment by amotenko** [comment]
Done. Currently grayed out since when hiding it looks weird. Will consider hiding when new design rolls out.
